version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: aml_fraud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adarsh2005
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/adarsh2005
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - neo4j
    environment:
      DATABASE_URL: postgresql://postgres:adarsh2005@postgres:5432/aml_fraud_db
      NEO4J_URI: bolt://neo4j:7687

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  neo4j_data: